
<?php

return [
    'per_page' => 15,

    'purchase_status' => ["unpaid", "paid"],

    'genders' => ['male', 'female'],

    'media_types' => ['image', 'audio', 'video', 'document'],

    'address_types' => ['home', 'work', 'other'],

    'office_types' => ['Head Office', 'Department', 'Branch'],

    'purchase_requisition_status' => ['Pending', 'Approved', 'Cancel'],

    'religions' => [
        'christianity',
        'islam',
        'hinduism',
        'buddhism',
        'others'
    ],

    'marital_statuses' => [
        'married',
        'single',
    ],

    'user_status' => [
      'Active',
      'Deactivate',
    ],

    'sales_payment_mode' => ['Cash', 'Checque'],
    
    'sales_payment_status' => ['Paid', 'Due', 'Return'],

    'unit_types' => [
        'Unit',
        'Box',
        'Nos',
        'Pair',
        'Set',
        'Meter',
        'Barleycorn',
        'Calibre',
        'Cable Length (UK)',
        'Cable Length (US)',
        'Cable Length',
        'Centimeter',
        'Chain',
        'Decimeter',
        'Ells (UK)',
        'Ems(Pica)',
        'Fathom',
        'Foot',
        'Furlong',
        'Hand',
        'Hectometer',
        'Inch',
        'Kilometer',
        'Link',
        'Micrometer',
        'Mile',
        'Mile (Nautical)',
        'Millimeter',
        'Nanometer',
        'Rod',
        'Vara',
        'Versta',
        'Yard',
        'Arshin',
        'Sazhen',
        'Medio Metro',
        'Square Meter',
        'Centiarea',
        'Area',
        'Manzana',
        'Caballeria',
        'Square Kilometer',
        'Are',
        'Acre',
        'Acre (US)',
        'Hectare',
        'Square Yard',
        'Square Foot',
        'Square Inch',
        'Square Centimeter',
        'Square Mile',
        'Meter/Second',
        'Inch/Minute',
        'Foot/Minute',
        'Inch/Second',
        'Kilometer/Hour',
        'Foot/Second',
        'Mile/Hour',
        'Knot',
        'Mile/Minute',
        'Mile/Second',
        'Carat',
        'Cental',
        'Dram',
        'Grain',
        'Gram',
        'Hundredweight (UK)',
        'Hundredweight (US)',
        'Quintal',
        'Kg',
        'Microgram',
        'Milligram',
        'Ounce',
        'Pood',
        'Pound',
        'Slug',
        'Stone',
        'Tonne',
        'Kip',
        'Barrel(Beer)',
        'Barrel (Oil)',
        'Bushel (UK)',
        'Bushel (US Dry Level)',
        'Centilitre',
        'Cubic Centimeter',
        'Cubic Decimeter',
        'Cubic Foot',
        'Cubic Inch',
        'Cubic Meter',
        'Cubic Millimeter',
        'Cubic Yard',
        'Cup',
        'Decilitre',
        'Fluid Ounce (UK)',
        'Fluid Ounce (US)',
        'Gallon (UK)',
        'Gallon Dry (US)',
        'Gallon Liquid (US)',
        'Litre',
        'Millilitre',
        'Peck',
        'Pint (UK)',
        'Pint, Dry (US)',
        'Pint, Liquid (US)',
        'Quart (UK)',
        'Quart Dry (US)',
        'Quart Liquid (US)',
        'Tablespoon (US)',
        'Teaspoon',
        'Day',
        'Hour',
        'Minute',
        'Second',
        'Millisecond',
        'Microsecond',
        'Nanosecond',
        'Week',
        'Atmosphere',
        'Pascal',
        'Bar',
        'Foot Of Water',
        'Hectopascal',
        'Iches Of Water',
        'Inches Of Mercury',
        'Kilopascal',
        'Meter Of Water',
        'Microbar',
        'Milibar',
        'Millimeter Of Mercury',
        'Millimeter Of Water',
        'Technical Atmosphere',
        'Torr',
        'Dyne',
        'Gram-Force',
        'Joule/Meter',
        'Kilogram-Force',
        'Kilopond',
        'Kilopound-Force',
        'Newton',
        'Ounce-Force',
        'Pond',
        'Pound-Force',
        'Poundal',
        'Tonne-Force(Metric)',
        'Ton-Force (UK)',
        'Ton-Force (US)',
        'Btu (It)',
        'Btu (Th)',
        'Btu (Mean)',
        'Calorie (It)',
        'Calorie (Th)',
        'Calorie (Mean)',
        'Calorie (Food)',
        'Erg',
        'Horsepower-Hours',
        'Inch Pound-Force',
        'Joule',
        'Kilojoule',
        'Kilocalorie',
        'Kilowatt-Hour',
        'Litre-Atmosphere',
        'Megajoule',
        'Watt-Hour',
        'Btu/Hour',
        'Btu/Minutes',
        'Btu/Seconds',
        'Calorie/Seconds',
        'Horsepower',
        'Kilowatt',
        'Megawatt',
        'Volt-Ampere',
        'Watt',
        'Centigram/Litre',
        'Decigram/Litre',
        'Dekagram/Litre',
        'Hectogram/Litre',
        'Gram/Cubic Meter',
        'Gram/Cubic Centimeter',
        'Gram/Cubic Millimeter',
        'Gram/Litre',
        'Grain/Gallon (US)',
        'Grain/Gallon (UK)',
        'Grain/Cubic Foot',
        'Kilogram/Cubic Meter',
        'Kilogram/Cubic Centimeter',
        'Kilogram/Litre',
        'Milligram/Cubic Meter',
        'Milligram/Cubic Centimeter',
        'Milligram/Cubic Millimeter',
        'Megagram/Litre',
        'Milligram/Litre',
        'Microgram/Litre',
        'Nanogram/Litre',
        'Ounce/Cubic Inch',
        'Ounce/Cubic Foot',
        'Ounce/Gallon (US)',
        'Ounce/Gallon (UK)',
        'Pound/Cubic Inch',
        'Pound/Cubic Foot',
        'Pound/Cubic Yard',
        'Pound/Gallon (US)',
        'Pound/Gallon (UK)',
        'Psi/1000 Feet',
        'Slug/Cubic Foot',
        'Ton (Short)/Cubic Yard',
        'Ton (Long)/Cubic Yard',
        'Celsius',
        'Fahrenheit',
        'Kelvin',
        'Cycle/Second',
        'Nanohertz',
        'Millihertz',
        'Hertz',
        'Kilohertz',
        'Megahertz',
        'Wavelength In Gigametres',
        'Wavelength In Megametres',
        'Wavelength In Kilometres',
        'Ampere-Hour',
        'Ampere-Minute',
        'Ampere-Second',
        'Coulomb',
        'EMU Of Charge',
        'Faraday',
        'Kilocoulomb',
        'Megacoulomb',
        'Millicoulomb',
        'Nanocoulomb',
        'Ampere',
        'Abampere',
        'Biot',
        'EMU of current',
        'Kiloampere',
        'Milliampere',
        'Gamma',
        'Gauss',
        'Tesla',
        'Percent',
        'Parts Per Million',
    ]
];
